image: registry.nic.cz/knot/respdiff-rs/ci

variables:
  LC_ALL: C.UTF-8

stages:
  - build
  - test
  - release

rust-latest:
  stage: build
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

fmt:
  stage: test
  script:
    - cargo fmt -- --check

clippy:
  stage: test
  script:
    - cargo clippy -- -D "warnings"

msgdiff:
  stage: test
  script:
    - cargo run -- diff-answers -e /lmdb/msgdiff-json -c test/msgdiff-json/respdiff.cfg -d msgdiff-rs.json
    - if [ -n "$(jd -set msgdiff-rs.json test/msgdiff-json/msgdiff.json)" ]; then exit 1; fi
  after_script:
    # run once again to obtain cmd output (YUCK)
    - jd -set msgdiff-rs.json test/msgdiff-json/msgdiff.json

release-dev:
  stage: release
  only:
    - master
  script:
    - cargo build --release
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file target/release/respdiff "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/respdiff-dev/master/respdiff"'

release:
  stage: release
  only:
    - tags
  script:
    - cargo build --release
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file target/release/respdiff "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/respdiff/$CI_COMMIT_TAG/respdiff"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file target/release/respdiff "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/respdiff/latest/respdiff"'
