image: rust:latest

variables:
  LC_ALL: C.UTF-8

stages:
  - build
  - test

rust-latest:
  stage: build
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

fmt:
  stage: test
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

clippy:
  stage: test
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -- -D "warnings"
