[package]
name = "respdiff"
version = "0.1.0"
authors = ["Tomas Krizek <tomas.krizek@nic.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "respdiff"
path = "src/lib/lib.rs"

[[bin]]
name = "transceiver"
path = "src/bin/transceiver.rs"

[dependencies]
lmdb-rkv = "0.14.0"
